server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debtpulse_contact?createDatabaseIfNotExist=true&serverTimezone=UTC
  flyway:
    locations: classpath:db/migration
    schemas: debtpulse_contact

logging:
  file:
    name: logs/spring.log
